name: CI 
run-name: Testing Proforma Code
on: [push]
env:
  JULIA_CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: list files in repo
      run: ls ${{ github.workspace }}
    - name: show Project.toml 
      run: cat Project.toml 
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'
    - run: julia -e 'println("Hello, World!")'
  codecov:
    runs-on: ubuntu-latest
    needs: test
    steps: 
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'
    - uses: julia-actions/julia-buildpkg@v1
    - name: verify CI environment
      run: |
        echo ${{ github.workflow }} 
        julia -e '@show get(ENV, "JULIA_CI", "nothing") == "true"'
    - uses: actions/checkout@v4
      with: 
        repository: 'ledger/ledger.git'
        ref: 'master'
        path: 'ledger'
        token: ${{ github.token }}
    - name: Configure Ledger-CLI
      run: | 
        cd ledger 
        sudo apt-get install build-essential cmake doxygen libboost-system-dev libboost-dev python3-dev gettext git libboost-date-time-dev libboost-filesystem-dev libboost-iostreams-dev libboost-python-dev libboost-regex-dev libboost-test-dev libedit-dev libgmp3-dev libmpfr-dev texinfo tzdata
        ./acprep update  # Update to the latest, configure, make
        sudo make install
        ledger --version
    - uses: julia-actions/julia-runtest@v1
    - uses: julia-actions/julia-processcoverage@v1
    - uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
